### PR TITLE
Chester Data + Parser

### PR DESCRIPTION
**Pull request by mjgaughan**
The data for Chester county and the parser used for it (Chester was a weird format). Also, not sure of where to put this, but I'm working on a parser that can take in multiple pdfs and return multiple csvs.

### CODE REVIEW

**Comment by mjgaughan** [comment]
Disregard the second sentence of the above comment. Way too much variation to make it worthwhile.

**Comment by dwillis** [comment]
@mjgaughan thanks - it's a shame that they are so varied because we have a ton of these PDFs, not just in PA but TX, UT and other states.

**Comment by rbier** [comment]
Hi @mjgaughan, saw you were interested in creating a generic pdf parser above. Even though Chester was a weird format, it looks like Schuylkill and Tioga are very similar, along with some datasets that haven't be put in `openelections-sources-pa` like Northampton. Do you want to lead creating a global parser for all of these? Anything I can do to help?

**Comment by mjgaughan** [comment]
Hey @rbier, going to DM you on Twitter to talk more in-depth about this project!

**Pull request merged**
