### PR TITLE
Bucks + Blair Primary Results

### PR DESCRIPTION
**Pull request by mjgaughan**
Also included a scraper I used for Bucks because it was unique.

### CODE REVIEW

**Comment by dwillis** [comment]
@mjgaughan Thanks - I've merged this and then saw a couple of things with Blair (which, to be fair, is giant). I'll clean them up on my end, but they mostly dealt with numeric/percentage values for `candidate`.

**Comment by mjgaughan** [comment]
@dwillis My apologies! I'll try to look over the data closer next time.

**Comment by dwillis** [comment]
@mjgaughan No worries - and for Bucks, it looks like we're missing these offices: Representative in Congress & Representative in the General Assembly.

**Comment by mjgaughan** [comment]
@dwillis Ok! I'll go back in and make sure those are added. Thanks for letting me know about that mistake.

**Comment by dwillis** [comment]
@mjgaughan I really appreciate your work on this.

**Comment by mjgaughan** [comment]
@dwillis Of course!! I just pulled the updated Bucks files in a new request

**Pull request merged**
