### PR TITLE
Bradford Parser

### PR DESCRIPTION
**Pull request by mjgaughan**
Having an issue with the Bradford results, was wondering if anyone could give me some help and look over this parser. Been stuck on an index out of range error on line 26 for a couple of days.

### CODE REVIEW

**Comment by dwillis** [comment]
@mjgaughan hey, will take a look and see what I can figure out. thanks!

**Comment by mjgaughan** [comment]
@dwillis Thank you!!

**Comment by dwillis** [comment]
@mjgaughan sorry it has taken me so long to get to this, but here's what I found. First, I just had it skip pages with 'DELEGATE' in `text_on_page`: 

```
if "PRESIDENT OF THE UNITED STATES" in text_on_page:
        presidental_race(text_on_page, csv_writer, office, party)
    elif number_of_races == 1:
        single_race(text_on_page,csv_writer)
    elif any('DELEGATE' in item for item in text_on_page):
        pass
    else:
        double_race_page(text_on_page, csv_writer)
```

That got me to the end of the Democratic races, but the GOP presidential race also yields a `IndexError: list index out of range` error, but for different reasons. Here's the list of presidential candidates from `text_on_page`:

```
['DONALD J.', 'TRUMP', 'ROQUE', 'ROCKY DE LA', 'FUENTE', 'BILL WELD', 'BERNIE', 'SANDERS', '(W)', 'JOSEPH', 'BIDEN  (W)']
```

It has 11 elements, so it can't be split up neatly by two. You could hard-code the presidential candidates, though.

**Comment by mjgaughan** [comment]
@dwillis thanks so much for looking into it! Might just hard-code in the presidential candidates at this point. I do see that Tulsi Gabbard is missing from the list from `text_on_page`? I'll also look into that and how to make sure she is included...thanks so much for the help!

**Comment by rbier** [comment]
Hi @mjgaughan -- I just joined as a volunteer, grabbed a dataset, created a [pull request](https://github.com/openelections/openelections-data-pa/pull/39) and.... stupidly didn't realize that you had already started working on this.

So, I feel like there are a few options here, let me know which you'd prefer:
* The "fast as possible" approach: my pull request has a parser and csv output for what I believe is the full dataset for Bradford, maybe you can do a code review of my PR, then we iterate on that
* The "lets get your code working" approach: I code review your code, we iterate on yours until we get a full dataset, and use my existing dataset to compare and verify everything works correctly
* The "something in between" approach: use my pull request, but also iterate on your pull request to validate my existing dataset, and determine the best way for us to work alongside each other on a few datasets (whether it be code review, creating some common code for processing, knowledge sharing, etc)
* The "I screwed up, and should go somewhere else" approach: you continue working on Bradford, I abandon my code and grab a different set of tables

**Comment by dwillis** [comment]
@rbier @mjgaughan this is on me - I should have told @rbier that @mjgaughan was already working on Bradford, and I apologize for not doing so. I'll let @mjgaughan weigh in, but fwiw my preference would be the 1st approach and then maybe trying similar but slightly different PDFs to see if @rbier's work can't be extended?

**Comment by mjgaughan** [comment]
I agree with @dwillis, I've been having a lot of issues w Bradford so if @rbier has a parser that works I would love to just glance it over and we all can be done with it. So glad someone figured it out!

**Comment by rbier** [comment]
Thanks for understanding, @dwillis and @mjgaughan. I'll be on the lookout for conflicts in the future 😛  @mjgaughan, I'll be working on Columbia county next since it can probably recycle my existing parser

**Pull request closed without merging**
