### PR TITLE
Creating Beaver and Centre 2020 Primary Results

### PR DESCRIPTION
**Pull request by mjgaughan**
Included parsers used for both. Minimal differences between parsers, both unique to results from county.

### CODE REVIEW

**Comment by mjgaughan** [comment]
Also included was Juniata, Mifflin, Clearfield counties. For Mifflin County, absentee mail-in and mail-in data was counted under "early_voting".

**Comment by dwillis** [comment]
@mjgaughan thanks! at the risk of sounding greedy, any chance Mifflin can be broken out by each category?

**Comment by mjgaughan** [comment]
Sure! How do you mean? Have the mail-ins as their own columns?

**Comment by dwillis** [comment]
Yeah, have `election_day`, `absentee`, `mail` and `absentee_mail` as vote types.

**Comment by mjgaughan** [comment]
Sure thing! I can do that!!

**Comment by mjgaughan** [comment]
Updated!

**Pull request merged**
