### PR TITLE
Bradford parser and results, 2020 Primary

### PR DESCRIPTION
**Pull request by rbier**
Bradford parser and results, 2020 Primary. This is my first parser and csv generator, so please let me know if there is anything I'm missing, misunderstanding, etc. Thanks!

Parser might be a bit heavyweight; my goal is that some of the logic could be reusable for other elections (looks like Columbia County has a similar format). The way the parser is structured is as follows:
* `pdf_to_csv` -> iterates pdf pages via `PDFPageIterator` -> create a `PDFPageParser` -> iterate rows
* Each `PDFPageParser` validates the header, extracts the table header with the `TableHeaderParser`, and preps the row iterator with `TableBodyParser`
* The `TableHeaderParser` will use the previous page's header if the previous page's office is still being processed; it will also validate the current page's header against the previous one. Otherwise, it does some pretty nasty intuiting of when the headers and subheaders begin and end, generally looking for the phrases "Jurisdiction Wide", "Write-in", "Turnout", and "Reg. Voters"
* The `TableBodyParser` will pivot the rows and columns of a given page into the standard OpenElections format.
* `TableHeader` object manages all the candidate header information, including extracting party, office, and district where possible. The candidate names themselves were in multiple string objects, so there is a huge `VALID_SUBHEADERS` definition, along with mapping improperly parsed and write-in candidates in `SUBHEADER_TO_CANDIDATE_MAPPING`, otherwise it's unclear where one candidate ends and another begins.

### CODE REVIEW

**Comment by dwillis** [comment]
@rbier thanks for this! It looks pretty good to me; the only things I see are some missing `party` values for the 68th district assembly race and the 12th district congressional race. If those aren't parseable from the PDF that's ok, we can backfill.

**Comment by rbier** [comment]
Good catch, I updated the logic and regenerated the csv -- I didn't appreciate that on a given page, if the first column shows `(DEMOCRATIC)` or `(REPUBLICAN)`, that also applies to the second column

**Comment by rbier** [comment]
Hi @dwillis, heads up that the Columbia County parser and data are ready to go, and will be leveraging the code in this PR. I'll share a PR for Columbia County once this PR is finalized and merged, but if it's easier to review both counties at once, I can merge my Columbia County parser and shared logic into this PR instead.

**Comment by dwillis** [comment]
@rbier sounds good - so this one is good to go from your standpoint?

**Comment by rbier** [comment]
Yes, with one caveat -- it's missing the Registered Voters and Ballots Cast. I added those with the shared logic for the Columbia parser

**Comment by dwillis** [comment]
@rbier yeah, let's merge the Columbia code into this PR.

**Comment by rbier** [comment]
@dwillis sounds good, just updated

**Comment by dwillis** [comment]
@rbier Thanks! This looks good - one small thing: we list Registered Voters and Ballots Cast as `office` and leave `candidate` blank.

**Comment by rbier** [comment]
No prob, code has been patched and csvs regenerated.

**Comment by dwillis** [comment]
@rbier

**Pull request merged**
