### PR TITLE
added county generals

### PR DESCRIPTION
**Pull request by alipman88**
~Draft PR. I think I have a few questions about format conventions to work out before I'm ready to submit this, but figured I'd at least stake out my claim on these sixteen counties.~

Ready for review!

### CODE REVIEW

**Comment by warwickmm** [comment]
Thanks @alipman88.  A few of the files appear to have an inconsistent number of columns.  For example, the header has 6 entries while some rows have 10:

image

Are there a few entries missing in the column headers?

https://github.com/openelections/openelections-data-pa/actions/runs/3798196515/jobs/6459728260

**Comment by alipman88** [comment]
@warwickmm - whoops, thanks for catching that. (I have a script that parses Electionware PDFs mostly automatically, but still requires some manual header adjustment as a last step, which I forgot.)

Since I'm a first-time contributor, can you approve me to run workflows? Thanks!

(https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)

**Comment by dwillis** [comment]
@alipman88 thanks - I approved the checks.

**Comment by alipman88** [comment]
I believe my work's ready to be merged.

I've standardized candidate names & offices, and filled in missing U.S. House & state legislative district numbers for counties that didn't include them in the PDFs (e.g. [Huntington](https://github.com/openelections/openelections-sources-pa/blob/master/2022/general/Huntingdon%20PA%20Official%20Precinct%20Summary_Nov%2022.pdf)).

**Pull request merged**
